name: Deploy PBI Theme to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Theme via FTP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: FTP Deploy Theme files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: argos.serverpanel.id
        username: bengkela
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        local-dir: ./pbi-company-profile/
        server-dir: /public_html/wp-content/themes/pbi-company-profile/
